defaults:
  - optimizer: adam
  - embeddings: restaurant
  
datapath: C:/Users/Jiwon/Desktop/abaedataset/preprocessed_data/restaurant/train.txt


batch_size: 50
ortho_reg: 0.2
aspects_number: 25
epochs: 1
negative_samples: 5
max_len: 201
log_progress_steps: 1000
w2v_vector_size: 200

hydra:
  job:
    config:
      override_dirname:
        exclude_keys:
          - model.log_progress_steps:

  help:
    template:
      "This is the script for training ABAE reimplemented in PyTorch"
